### ISSUE TITLE
[meta] Merge repo into web-platform-tests

### ISSUE THREAD

**Issue by csswg-test-issue-mover** [w3c/web-platform-tests#5486]
Originally posted as https://github.com/w3c/csswg-test/issues/1102 by @gsnedders on 29 Jul 2016, 16:54 UTC:

> From <https://lists.w3.org/Archives/Public/www-style/2016Oct/0088.html>:
> 
> - [x] Land https://github.com/w3c/wpt-tools/pull/90 into wpt-tools so that the web-platform-tests tools create an accurate manifest (i.e., list of tests) for the CSS testsuite.
> - [x] Add a number of lints to wpt-tools, for the (currently non-existent) css subdirectory, to ensure that the build system keeps working (primarily we need lints to ensure that we have no duplicate file-extensionless-basenames that aren't byte-for-byte identical and that all files referenced by test files are in an adjacent support or reference directory, with a couple of exceptions).
> - [x] Ensure web-platform-tests's documentation is up-to-date and cohesive, both for submitting tests and reviewing them. Especially make sure it's easier to find documentation than it is currently!
> - [x] Make https://hg.csswg.org/test/ and http://test.csswg.org/shepherd/ read-only. (This only depends on making sure we have something in way of GitHub documentation; #1101 )
> - [x] Merge csswg-test into web-platform-tests, in a css/ subdirectory, maintaining all csswg-test history, with w3ctestlib and apiclient being moved over to git submodules.
> - [ ] Move over, at the very least, all open issues and PRs from the csswg-test repository.
> - [ ] (Sometime in the more distant future) drop the current build system and the lints we had for its requirements.

---

Still remaining (2017-04-07):

 - [x] Move over all remaining issues (these are things labelled with type:missing-coverage *and* spec:regions or spec:compositing) into two new meta-issues per-spec
 - [x] Wait for editors of the Masking spec to decide if they want to spend time to move https://github.com/w3c/csswg-test/pull/430 over
 - [ ] Merge https://github.com/w3c/csswg-test/pull/810 from csswg-test into web-platform-tests by magic once it's been reviewed and accepted

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1102#issuecomment-289907916 by @gsnedders on 28 Mar 2017, 21:18 UTC:

> The merge itself is now done. WOOOOO.

**Comment by gsnedders** [comment]
still not merged, but no progress there and keeping this open helps nobody really
