### ISSUE TITLE
Missing Compositing tests

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5555]
These have been moved over from bulk from csswg-test; each of these issues gives a test case description and an expected result. However, due to the age of these issues it should be checked that this expected result still matches the spec.

If you believe any of these issues needs discussion prior to working on it, please file a new issue here to discuss it.

If you write any tests for these, please link to this issue and make sure someone marks it as done here.

 - [ ] [Simple &lt;div>](https://github.com/w3c/csswg-test/issues/219)
 - [ ] [Blending &lt;video>](https://github.com/w3c/csswg-test/issues/221)
 - [ ] [Blending with a sibling](https://github.com/w3c/csswg-test/issues/222)
 - [ ] [Blending with two levels of ascendants](https://github.com/w3c/csswg-test/issues/223)
 - [ ] [Parent with transparent pixels](https://github.com/w3c/csswg-test/issues/225)
 - [ ] [Parent with border-radius](https://github.com/w3c/csswg-test/issues/226)
 - [ ] [Child of the blended element has opacity](https://github.com/w3c/csswg-test/issues/227)
 - [ ] [Overflowed child of the blended element](https://github.com/w3c/csswg-test/issues/228)
 - [ ] [Blended element with transparent pixels](https://github.com/w3c/csswg-test/issues/229)
 - [ ] [Parent with 3D transform](https://github.com/w3c/csswg-test/issues/230)
 - [ ] [Blended element with 3D transform](https://github.com/w3c/csswg-test/issues/231)
 - [ ] [Both parent and blended element with 3D transform](https://github.com/w3c/csswg-test/issues/232)
 - [ ] [Blended element with transform and preserve-3d](https://github.com/w3c/csswg-test/issues/233)
 - [ ] [Blended element with transform and perspective](https://github.com/w3c/csswg-test/issues/234)
 - [ ] [Sibling with 3D transform between the parent and the blended element](https://github.com/w3c/csswg-test/issues/235)
 - [ ] [Parent with 3D transform and transition](https://github.com/w3c/csswg-test/issues/236)
 - [ ] [Sibling with 3D transform(and transition) between the parent and the blended element](https://github.com/w3c/csswg-test/issues/237)
 - [ ] [Parent element with overflow:scroll](https://github.com/w3c/csswg-test/issues/238)
 - [ ] [Blended element with overflow:scroll](https://github.com/w3c/csswg-test/issues/239)
 - [ ] [Parent element with overflow:scroll and blended with position:fixed](https://github.com/w3c/csswg-test/issues/240)
 - [ ] [Parent with overflow:hidden and border-radius](https://github.com/w3c/csswg-test/issues/241)
 - [ ] [Blended element with overflow:hidden and border-radius](https://github.com/w3c/csswg-test/issues/242)
 - [ ] [Intermediate child with overflow:hidden and border-radius between the parent and the blended element](https://github.com/w3c/csswg-test/issues/243)
 - [ ] [Blended element with border-image](https://github.com/w3c/csswg-test/issues/244)
 - [ ] [Blending with &lt;canvas>](https://github.com/w3c/csswg-test/issues/245)
 - [ ] [Blended &lt;canvas>](https://github.com/w3c/csswg-test/issues/246)
 - [ ] [Blended &lt;video>](https://github.com/w3c/csswg-test/issues/247)
 - [ ] [Blending with &lt;iframe>](https://github.com/w3c/csswg-test/issues/248)
 - [ ] [Blended &lt;iframe>](https://github.com/w3c/csswg-test/issues/249)
 - [ ] [Blended element with mask property](https://github.com/w3c/csswg-test/issues/250)
 - [ ] [Blended element with clip-path property](https://github.com/w3c/csswg-test/issues/251)
 - [ ] [Blended element with filter property](https://github.com/w3c/csswg-test/issues/252)
 - [ ] [Blended element with transition](https://github.com/w3c/csswg-test/issues/253)
 - [ ] [Blended element with animation](https://github.com/w3c/csswg-test/issues/254)
 - [ ] [Image element](https://github.com/w3c/csswg-test/issues/255)
 - [ ] [SVG element](https://github.com/w3c/csswg-test/issues/256)
 - [ ] [Paragraph element](https://github.com/w3c/csswg-test/issues/257)
 - [ ] [Paragraph element and background-image](https://github.com/w3c/csswg-test/issues/258)
 - [ ] [Set blending from JavaScript](https://github.com/w3c/csswg-test/issues/259)
 - [ ] [Sibling with 3D transform(and transition) between the parent and the blended element](https://github.com/w3c/csswg-test/issues/260)
 - [ ] [Isolation on intermediate element with transparent pixels](https://github.com/w3c/csswg-test/issues/261)
 - [ ] [Circle with SVG background](https://github.com/w3c/csswg-test/issues/262)
 - [ ] [Ellipse with SVG background](https://github.com/w3c/csswg-test/issues/263)
 - [ ] [Image with SVG background](https://github.com/w3c/csswg-test/issues/264)
 - [ ] [Line with SVG background](https://github.com/w3c/csswg-test/issues/265)
 - [ ] [Path with SVG background](https://github.com/w3c/csswg-test/issues/266)
 - [ ] [Polygon with SVG background](https://github.com/w3c/csswg-test/issues/267)
 - [ ] [Rect with SVG background](https://github.com/w3c/csswg-test/issues/269)
 - [ ] [Text having tspan with SVG background](https://github.com/w3c/csswg-test/issues/271)
 - [ ] [Gradient with SVG background](https://github.com/w3c/csswg-test/issues/272)
 - [ ] [Pattern with SVG background](https://github.com/w3c/csswg-test/issues/273)
 - [ ] [Set blending on an element from JavaScript](https://github.com/w3c/csswg-test/issues/274)
 - [ ] [Marker with SVG background](https://github.com/w3c/csswg-test/issues/275)
 - [ ] [Metadata with SVG background](https://github.com/w3c/csswg-test/issues/276)
 - [ ] [ForeignObject with SVG background](https://github.com/w3c/csswg-test/issues/277)
 - [ ] [Group of overlapping elements with SVG background](https://github.com/w3c/csswg-test/issues/278)
 - [ ] [Blending two elements in an isolated group](https://github.com/w3c/csswg-test/issues/279)
 - [ ] [Blending in a group with filter](https://github.com/w3c/csswg-test/issues/281)
 - [ ] [Blending in a group with 2D transform](https://github.com/w3c/csswg-test/issues/282)
 - [ ] [Blending in a group with 3D transform](https://github.com/w3c/csswg-test/issues/283)
 - [ ] [Blending in a group with a mask](https://github.com/w3c/csswg-test/issues/284)
 - [ ] [Blending in a group with mix-blend-mode](https://github.com/w3c/csswg-test/issues/285)
 - [ ] [Blend with element having opacity](https://github.com/w3c/csswg-test/issues/286)
 - [ ] [Blend with element having stroke](https://github.com/w3c/csswg-test/issues/287)
 - [ ] [Blend with element having stroke-opacity](https://github.com/w3c/csswg-test/issues/288)
 - [ ] [Blend with element having stroke-dasharray](https://github.com/w3c/csswg-test/issues/289)
 - [ ] [Blend with element having transform](https://github.com/w3c/csswg-test/issues/290)
 - [ ] [Blend with SVG having viewbox and preserveAspectRatio set](https://github.com/w3c/csswg-test/issues/291)
 - [ ] [Blend with an element having color-profile set](https://github.com/w3c/csswg-test/issues/292)
 - [ ] [Blend with an element having overflow](https://github.com/w3c/csswg-test/issues/293)
 - [ ] [Blend with an element having clip-path](https://github.com/w3c/csswg-test/issues/294)
 - [ ] [Blend with an element having a mask](https://github.com/w3c/csswg-test/issues/295)
 - [ ] [Blend with an element having a filter](https://github.com/w3c/csswg-test/issues/296)
 - [ ] [Blend with an animated element](https://github.com/w3c/csswg-test/issues/297)
 - [ ] [Set blending from an SVG script element](https://github.com/w3c/csswg-test/issues/298)
 - [ ] [Blending two elements in an isolated group - SVG isolation:isolate](https://github.com/w3c/csswg-test/issues/299)
 - [ ] [Isolate inside a stacking context created by a 3d transform](https://github.com/w3c/csswg-test/issues/300)
 - [ ] [Images with different formats](https://github.com/w3c/csswg-test/issues/301)
 - [ ] [Gradient and background color](https://github.com/w3c/csswg-test/issues/302)
 - [ ] [Image and gradient](https://github.com/w3c/csswg-test/issues/303)
 - [ ] [Gradient and image](https://github.com/w3c/csswg-test/issues/304)
 - [ ] [Two gradients](https://github.com/w3c/csswg-test/issues/305)
 - [ ] [Two images](https://github.com/w3c/csswg-test/issues/306)
 - [ ] [One background layer](https://github.com/w3c/csswg-test/issues/308)
 - [ ] [Two elements](https://github.com/w3c/csswg-test/issues/309)
 - [ ] [Different blend modes applied between layers](https://github.com/w3c/csswg-test/issues/310)
 - [ ] [Blend mode list repeat](https://github.com/w3c/csswg-test/issues/311)
 - [ ] [Default blend mode for 'background' shorthand](https://github.com/w3c/csswg-test/issues/312)
 - [ ] [background-position percentage](https://github.com/w3c/csswg-test/issues/313)
 - [ ] [Background size defined in pixels](https://github.com/w3c/csswg-test/issues/314)
 - [ ] [Background size defined in percentage (second phase)](https://github.com/w3c/csswg-test/issues/315)
 - [ ] [Background size cover](https://github.com/w3c/csswg-test/issues/316)
 - [ ] [Background size contain](https://github.com/w3c/csswg-test/issues/317)
 - [ ] [background-repeat set to no-repeat](https://github.com/w3c/csswg-test/issues/318)
 - [ ] [background-clip set to padding-box](https://github.com/w3c/csswg-test/issues/319)
 - [ ] [background-clip set to content-box](https://github.com/w3c/csswg-test/issues/320)
 - [ ] [background-origin set to border-box](https://github.com/w3c/csswg-test/issues/321)
 - [ ] [background-attachment set to fixed](https://github.com/w3c/csswg-test/issues/323)
 - [ ] [Isolation isolate](https://github.com/w3c/csswg-test/issues/373)
 - [ ] [Isolation of blended child which overflows](https://github.com/w3c/csswg-test/issues/374)
 - [ ] [Isolation auto](https://github.com/w3c/csswg-test/issues/375)
 - [ ] [Stacking context not affected by isolation](https://github.com/w3c/csswg-test/issues/376)
 - [ ] [Blending in an isolated group](https://github.com/w3c/csswg-test/issues/377)
 - [ ] [Blending in an isolated group with 2D transform](https://github.com/w3c/csswg-test/issues/378)
 - [ ] [Set isolation on an element from JavaScript](https://github.com/w3c/csswg-test/issues/379)
 - [ ] [Blending a group with isolation:auto](https://github.com/w3c/csswg-test/issues/380)
 - [ ] [Blending in a group with opacity](https://github.com/w3c/csswg-test/issues/381)

**Comment by meyerweb** [comment]
This looks like all the issues have been closed separately.  True/false?

**Comment by gsnedders** [comment]
> This looks like all the issues have been closed separately. True/false?

False; they all got closed in the all csswg-test repo, as part of tidying up that repo. This predates GitHub having any way to move issues between repos, and I didn't see much point in manually (or rather, with-a-bot) copying over a huge number of issues which had already sat unattended for years.
