### ISSUE TITLE
Unowned directories

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5915]
We should make sure all top-level directories have at least one OWNER:

```
pnin:wpt2 gsnedders$ find . ./css -mindepth 1 -maxdepth 1 -type d '!' -exec test -e "{}/OWNERS" ';' -print
```
* [x] ./orientation-event #10764
* [x] ./worklets #10766
* [x] ./offscreen-canvas #10767
* [x] ./mediasession #10768
* [x] ./server-timing #10770
* [x] ./client-hints #10771
* [x] ./picture-in-picture #10763
* [x] ./css
* [x] ./js https://github.com/w3c/web-platform-tests/pull/10585
* [x] ./mediacapture-fromelement #10772
* [x] ./media-capabilities #10774
* [x] ./.well-known #10761
* [x] ./wasm #10775
* [x] ./acid https://github.com/w3c/web-platform-tests/pull/10585
* [x] ./apng #10777
* [x] ./webgl #10760
* [x] ./imagebitmap-renderingcontext #10767
* [x] ./upgrade-insecure-requests #10779
* [x] ./netinfo #10780
* [x] ./old-tests #10759
* [x] ./credential-management #10781
* [x] ./keyboard-lock #10782
* [x] ./2dcontext #10767
* [x] ./audio-output #10783
* [x] ./remote-playback #10784
* [x] ./secure-contexts #10779
* [x] ./device-memory #10785
* [x] ./trusted-types #10779
* [x] ./innerText https://github.com/w3c/web-platform-tests/pull/10583
* [x] ./budget-api #10758
* [x] ./clear-site-data #10787
* [x] ./infrastructure https://github.com/w3c/web-platform-tests/pull/10612
* [x] ./x-frame-options #11063
* [x] ./BackgroundSync #10757
* [x] ./mediacapture-image #10788
* [x] ./css/css-content https://github.com/w3c/web-platform-tests/pull/10508
* [x] ./css/css-sizing https://github.com/w3c/web-platform-tests/pull/10578
* [x] ./css/css-shadow-parts https://github.com/w3c/web-platform-tests/pull/10551
* [x] ./css/css-scroll-snap https://github.com/w3c/web-platform-tests/pull/10550
* [x] ./css/vendor-imports (the only subdirectory mozilla/ has an OWNERS file)
* [x] ./css/css-font-loading https://github.com/w3c/web-platform-tests/pull/10520
* [x] ./css/motion https://github.com/w3c/web-platform-tests/pull/10581
* [x] ./css/css-scroll-anchoring https://github.com/w3c/web-platform-tests/pull/10524
* [x] ./css/css-position https://github.com/w3c/web-platform-tests/pull/10521
* [x] ./css/css-fill-stroke https://github.com/w3c/web-platform-tests/pull/10519
* [x] ./css/css-properties-values-api https://github.com/w3c/web-platform-tests/pull/10522

Round 2:

* [x] ./keyboard-map #11087
* [x] ./async-local-storage #11088
* [x] ./css/css-filter #11089

**Comment by tobie** [comment]
wpt-pr-bot now adds a comments whenever there's a pr that has no OWNERS files.

Problem is the process we have to handle this at this point is to send the OP on irc. Seems subpar. Maybe suggest something else here and modify the comment wpt-pr-bot makes accordingly?

**Comment by gsnedders** [comment]
IMO, we should try and seek out people for all of these directories. I think most should be relatively easy?

**Comment by gsnedders** [comment]
@annevk http?

@halindrome annotation-protocol?

@miketaylr @annevk compat?

@fred-wang mathml?

**Comment by fred-wang** [comment]
> @fred-wang mathml?

Yes, I can take ownership for that one. Thanks.

**Comment by gsnedders** [comment]
@fred-wang done in https://github.com/w3c/web-platform-tests/commit/b0c089d479a61bc3d486dc880438782af2665917

**Comment by halindrome** [comment]
I can take annotation-protocol

**Comment by annevk** [comment]
Maybe @mnot wants to own `http/`? I'm okay with looking at PRs though.

**Comment by mnot** [comment]
Sure.

**Comment by foolip** [comment]
@gsnedders, which are still missing? I feel like I've added rather many in the past months.

**Comment by gsnedders** [comment]
@foolip updated

**Comment by foolip** [comment]
Thanks! Lots of those have OWNERS files in Chromium, so probably >50% of them could be fixed by copying those, converting to GitHub user names and sending out lots of reviews for people to find additional co-owners.

**Comment by zcorpan** [comment]
I updated the first comment with the current state. I've created PRs for a few CSS directories, getting names from the spec's editors.

**Comment by Ms2ger** [comment]
I can take `acid` and `js`

**Comment by zcorpan** [comment]
annevk on IRC
```
<annevk> zcorpan: seems innerText should mimic html
<annevk> zcorpan: x-frame-options should mimic csp
<annevk> zcorpan: another way of solving that might be to move some of those directories
```

**Comment by fantasai** [comment]
I think Tab and I would be happy to hand off ownership to anyone who wants it, but in the meantime it's probably fine to have us added to unowned modules we edit. (I can try to be more responsive wrt reviews going forward, but tbh I've been shit at responding to review requests in general.)

**Comment by annevk** [comment]
@grorg @junov thoughts on how to deal with all the canvas tests? Should we try to move those into html/ as they are part of that specification or is keeping them in separate top-level directories preferable for some reason? Any of you willing to review incoming PRs?

**Comment by junov** [comment]
@annevk I agree these should not be top level. I volunteer to review PRs.  There's a bunch of canvas tests in html/semantics/embedded-content/the-canvas-element, which IMHO should be closer to the other canvas tests in the directory structure.

**Comment by zcorpan** [comment]
There are now PRs for everything. If somebody feels they're missing or don't want to be listed, please comment in the PR. If you are added and approve, please mark as approved using GitHub's review feature.

**Comment by jugglinmike** [comment]
@zcorpan Way to go! Do you think we can lint for this once all those patches land?

**Comment by zcorpan** [comment]
Yep, that is https://github.com/w3c/web-platform-tests/issues/10552

**Comment by zcorpan** [comment]
I intend to go over the PRs tomorrow and remove non-responders and merge.

**Comment by zcorpan** [comment]
These are still not merged now:
* [Add .well-known/idp-proxy/OWNERS](https://github.com/w3c/web-platform-tests/pull/10761)
* [Add keyboard-lock/OWNERS](https://github.com/w3c/web-platform-tests/pull/10782)
* [ Move x-frame-options/ into content-security-policy/](https://github.com/w3c/web-platform-tests/pull/10594)

**Comment by gsnedders** [comment]
Running the command in the initial issue gives:

```
./keyboard-map
./x-frame-options
./.well-known
./css
./async-local-storage
./css/css-filter
./css/vendor-imports
```

I think `css` and probably `css/vendor-imports` are the only things that *shouldn't* have OWNERS files.

**Comment by zcorpan** [comment]
.well-known should have OWNERS in subdirs.

**Comment by zcorpan** [comment]
I think we have everything now. @gsnedders can you confirm?
