### ISSUE TITLE
Reftests are flaky in many browsers with wptrunner

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#6329]
Per-browser flaky bugs (checked when fixed):

- [x] [Chrome](https://github.com/w3c/web-platform-tests/issues/5412)
- [ ] [Edge](https://github.com/w3c/web-platform-tests/issues/6327)
- [x] [Safari](https://github.com/w3c/web-platform-tests/issues/6328)

**Comment by bobholt** [comment]
@gsnedders It's unclear if you're checking off ones that are still flaky or good. Can you add some clarifying comments?

**Comment by gsnedders** [comment]
@bobholt done

**Comment by foolip** [comment]
@gsnedders, do we have any use for this tracking issue, or should we just close it and keep https://github.com/w3c/web-platform-tests/issues/6327? The priorities aren't the same, which is weird given the connection :)
