### ISSUE TITLE
meta: Payment Request missing tests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-platform-tests#6489]
# Payment Request API - Testing plan

### Constructor
Owner: @marcoscaceres
* Test file: [payment-request-constructor.https.html](https://w3c-test.org/payment-request/payment-request-constructor.https.html)
  
### id attribute
Tested in files:
 * [payment-request-id.https.html](https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-id.https.html)
 * [https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor.https.html](https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor.https.html#L22-L52)

Missing tests: 
* [ ] stealing another payment requests id is allowed. 
* [ ] iterate over 1024 requests, making sure the ids are unique.

### onshippingoptionchange attribute

-----
### complete() method

-----
## SecureContexts
- [ ] Add test for absence of interfaces in insecure context, like #6566 

-----
## Events

-----
### User aborts the payment request algorithm

-----

**Comment by bentian** [comment]
- [ ] Revise/add tests for [toJSON change](https://github.com/w3c/browser-payment-api/issues/555)

**Comment by marcoscaceres** [comment]
Opening individual issues instead.
